site_name: "SploitKit - Devkit for building Metasploit-like consoles"
repo_url: https://github.com/dhondta/python-sploitkit
site_author: dhondta
docs_dir: docs
nav:
  - Introduction: index.md
  - 'Getting started': quickstart.md
  - Design: design.md
  - Classes: classes.md
  - Classes:
    - Entity: classes/entity.md
    - Console: classes/console.md
    - Command: classes/command.md
    - Module: classes/module.md
    - Datastore: classes/datastore.md
  - 'Base entities': base.md
  - 'Base entities':
    - Consoles: base/consoles.md
    - Commands: base/commands.md
    - Models: base/models.md
  - 'Real-life examples':
    - 'DroneSploit': examples/dronesploit.md
extra:
  mailto: alexandre.dhondt@gmail.com
theme: readthedocs
extra_javascript:
  - js/collapsible-navbar.js
use_directory_urls: false
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.details
  - toc:
      permalink: True
